### PR TITLE
fix html structure

### PR DESCRIPTION
**Pull request by Assimilationstheorie**

### CODE REVIEW

**Comment by NicolaeNMV** [comment]
Hm, looks like a bot..

**Comment by Assimilationstheorie** [comment]
When i try to help, you think i am a bot? Whats wrong with you?

**Comment by gre** [comment]
hold on, I don't think @NicolaeNMV meant any offence! But this project is "dead", I mean it was just a one-shot university project 6 years ago! feel free to fork it for sure, but there is no point maintaining it ;)

I prefixed the project with unmaintained_ like i usually do for all my old stuff :)

best regards

**Comment by NicolaeNMV** [comment]
Hello @Assimilationstheorie, my apologies. 

At first sight it looked like an automated action. Feel free to fork the project as Gre said.

All the best.

**Pull request closed without merging**
